AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: my-cluster2

  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: cloud-computing-demo
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: '256'
      Memory: '512'
      ContainerDefinitions:
        - Name: webapp
          Image: henkemike/cloud-computing-demo:latest
          Essential: true
          PortMappings:
            - ContainerPort: 3000

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 1
      TaskDefinition: !Ref ECSTaskDefinition
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - subnet-12345678
          SecurityGroups:
            - !Ref ECSSecurityGroup

  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow inbound traffic on port 3000
      VpcId: VALID_VPC_ID
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

Outputs:
  ServiceURL:
    Description: 'URL of the web application'
    Value: !Sub 'http://${AWS::StackName}.elb.amazonaws.com:3000'
